### ISSUE TITLE
ImportError: No module named 'requests'

### ISSUE THREAD

**Issue by sbrl** [pirate/bookmark-archiver#111]
I've just downloaded _Bookmark Archiver_ to take a look, but I'm getting a strange error:

```
Traceback (most recent call last):
  File "./archive", line 12, in <module>
    from parse import parse_links
  File "/mnt/elfstone/srv/bookmark-archiver/archiver/parse.py", line 26, in <module>
    from util import (
  File "/mnt/elfstone/srv/bookmark-archiver/archiver/util.py", line 6, in <module>
    import requests
ImportError: No module named 'requests'
```

Strange. If I try to install `requests` via pip (`sudo pip install requests`), I get this:

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (2.12.4)
````

**Comment by sbrl** [comment]
Upon further investigation, I found a solution!

```
sudo apt install python3-pip
sudo pip3 install requests
```
