### ISSUE TITLE
No moudle named distutils.dir_util

### ISSUE THREAD

**Issue by Eletroguy** [pirate/bookmark-archiver#93]
Trying to run the archiver on ubuntu 18.04 64 bit. I've followed the instructions to verify that all dependencies are installed and it can see chromium and everything, but I still get the error below.

```bash
./archive ~/Downloads/bookmarks.html 
Traceback (most recent call last):
  File "./archive", line 14, in <module>
    from archive_methods import archive_links, _RESULTS_TOTALS
  File "/home/eletroguy/books/Bookmarks/bookmark-archiver/archiver/archive_methods.py", line 11, in <module>
    from index import wget_output_path, parse_json_link_index, write_link_index
  File "/home/eletroguy/books/Bookmarks/bookmark-archiver/archiver/index.py", line 6, in <module>
    from distutils.dir_util import copy_tree
ModuleNotFoundError: No module named 'distutils.dir_util'
```

**Comment by pirate** [comment]
Looks like you're missing `python3-distutils`, I'll add it to the setup script, thanks!

For now, run:

```bash
apt install python3-distutils
```

**Comment by pirate** [comment]
Fixed: https://github.com/pirate/bookmark-archiver/commit/451cea47e68c3e202fd0b928cde1d4f0e3518572
